<?php
/**
 * Magento
 *
 * @author		ericyue2012@gmail.com
 * @version    24/02/2015
 */
?>

<?php /* Featured Product*/?>
<?php 
		// get all products that are marked as featured
		$collection = Mage::getModel('catalog/product')->getCollection();
		$collection->addAttributeToSelect('cc_feature_product');
		$collection->addAttributeToSelect('price');

		$collection->addFieldToFilter(array(
			array('attribute' => 'cc_feature_product', 'eq' => true),
		));
 
?>
<?php if ($collection->count()) : ?>

<div class="page-title category-title">
        <h1><?php echo $this->__('Featured Products') ?></h1>
</div>
<?php $_columnCount = 3; // $this->getColumnCount(); ?>
    <?php $i=0;
	
			foreach ($collection as $_product) :
			$_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId()); ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid row">
        <?php endif ?>
            <li class="item col-xs-4<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="wrapper-hover">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                    <div class="product-shop">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                        <div class="desc_grid"><?php $small_getDescription = strip_tags($_product->getShortDescription());
                             if (strlen($small_getDescription) < 70) echo($small_getDescription);
                             else { echo mb_substr($small_getDescription, 0, 70,'UTF-8').'...';} ?></div>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
						 <?php if($_product->getPrice()<5000): ?>
                        <div class="price-box">
                        	<span class="regular-price" id="product-price-2464-new">
                            	<span class="price">$<?php echo number_format($_product->getPrice(), 2);?></span>
                            </span>
        				</div>
                        <?php endif;?>
                        <div class="actions">
                            
                            <?php if($_product->isSaleable()): ?>
                            	<?php if($_product->getPrice()<5000):?>
                                    <button type="button" title="<?php echo 'Add to Cart'; ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo 'Add to Cart';?></span></span></button>
                                <?php else:?>
                                    <?php /*<button type="button" title="<?php echo $this->__('Add to Pending Quotes') ?>" class="button btn-cart btn-pending-quote" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Pending Quotes') ?></span></span></button>*/?>
                                    <div class="price-placeholder"></div>
                                    <button type="button" title="<?php echo 'Add to Quote'; ?>" class="button btn-cart btn-pending-quote" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><span><span><?php echo 'Add to Quote'; ?></span></span></button>
                                <?php endif;?>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>


                            <button type="button" title="<?php echo $this->__('Details') ?>" class="button btn-details btn-pending-quote-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Details') ?></span></span></button>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product)  ?>" class="link-wishlist"><?php echo $this->__('Add to Pending Quotes') ?></a></li>
                                 
                                <?php endif; ?>
                                <?php /*
								<?php if ($_compareUrl =$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
								*/?>
                            </ul>
                        </div>
                    </div>
                    <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                    <div class="label-product">             
                        <?php if($_product->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
                        <?php if($_product->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
                    </div>
                    <div class="clear"></div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif ?>
    <?php endforeach; ?>
<?php endif; ?>

